version: '3.8'

services:
  app:
    build: .
    container_name: quick-task-hub
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/taskdb
      - PORT=3000
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:7
    container_name: task-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data:
